import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { buildApp } from '../src/app.js';
import { centsToDecimal, decimalToCents, isValidMoneyString } from '../src/lib/money.js';

/**
 * Emit the contract the iOS repository builds against.
 *
 * The client lives in its own repository and cannot be verified against source
 * it does not have, so the contract is **generated and published** rather than
 * described in prose (D14).
 *
 *   contract/openapi.json        generated from the Zod schemas that serve the routes
 *   contract/money-vectors.json  decimal strings to integer cents
 *
 * Nothing here is hand-maintained. `openapi.json` comes from the running app,
 * so a route that does not exist cannot appear in it, and the vectors are
 * computed by the same functions the server uses — a vector file written by
 * hand would eventually disagree with the server and be believed.
 */

const CONTRACT_DIR = resolve(process.cwd(), 'contract');

/**
 * Inputs chosen because a plausible client implementation gets them wrong.
 *
 * The trap this file exists for is `Double(amountString)`. OpenAPI types money
 * as `string`, and nothing in a generated Swift client stops that — which
 * reintroduces float error on the screen where a person approves a payment.
 */
const VALID_CASES: Array<{ decimal: string; why?: string }> = [
  { decimal: '0.00' },
  { decimal: '0.01', why: 'smallest unit' },
  { decimal: '1.00' },
  { decimal: '12.34' },
  // The five below are the point of this file. Each one is a value where
  // `parseFloat(s) * 100` lands just under the integer, so an implementation
  // that truncates instead of rounding loses a cent — on some inputs only,
  // which is the worst way to be wrong.
  { decimal: '0.29', why: '0.29 * 100 is 28.999999999999996' },
  { decimal: '4.35', why: '4.35 * 100 is 434.99999999999994' },
  { decimal: '1.15', why: '1.15 * 100 is 114.99999999999999' },
  { decimal: '9.95', why: '9.95 * 100 is 994.9999999999999' },
  { decimal: '1.13', why: '1.13 * 100 is 112.99999999999999' },
  { decimal: '8.16', why: 'a near miss that does NOT trap; included so the set is not all traps' },
  { decimal: '-5.60', why: 'negative amounts behave identically' },
  { decimal: '0.1', why: 'one decimal place means ten cents, not one' },
  { decimal: '5', why: 'no decimal point at all' },
  { decimal: '999999999999.99', why: 'numeric(14,2) upper bound' },
  { decimal: '-999999999999.99', why: 'numeric(14,2) lower bound' },
];

/**
 * Rejected on purpose. A client that accepts these will eventually be handed
 * one by a bug somewhere else and will guess.
 */
const INVALID_CASES: Array<{ decimal: string; why: string }> = [
  { decimal: '2.675', why: 'three decimal places: rounding is a decision about money, not a parse' },
  { decimal: '1.2.3', why: 'not a number' },
  { decimal: '', why: 'empty' },
  { decimal: ' 1.00', why: 'leading whitespace' },
  { decimal: '1.00 ', why: 'trailing whitespace' },
  { decimal: '+1.00', why: 'explicit plus sign' },
  { decimal: '1e2', why: 'exponent notation' },
  { decimal: 'NaN', why: 'the float escape hatch, spelled out' },
  { decimal: 'Infinity', why: 'likewise' },
  { decimal: '1,234.00', why: 'thousands separator' },
  { decimal: '$1.00', why: 'currency symbol' },
  { decimal: '1234567890123.00', why: 'thirteen digits exceeds numeric(14,2)' },
];

function buildMoneyVectors(): unknown {
  const valid = VALID_CASES.filter((testCase) => isValidMoneyString(testCase.decimal)).map(
    (testCase) => ({
      decimal: testCase.decimal,
      cents: decimalToCents(testCase.decimal),
      // Round-tripping is part of the contract: cents back to a string must
      // always produce two decimal places.
      canonical: centsToDecimal(decimalToCents(testCase.decimal)),
      ...(testCase.why ? { why: testCase.why } : {}),
    }),
  );

  return {
    $comment:
      'Generated by scripts/emit-contract.ts. Do not edit by hand — a vector file that disagrees with the server would be believed.',
    description:
      'Money crosses the wire as a decimal string, never a float. Parse these to integer cents by string manipulation. Double(amountString) fails several of the cases below.',
    format: 'numeric(14,2): up to 12 digits before the point, exactly 0-2 after',
    valid,
    invalid: INVALID_CASES,
  };
}

async function main(): Promise<void> {
  mkdirSync(CONTRACT_DIR, { recursive: true });

  const app = await buildApp();
  const openapi = app.swagger();
  await app.close();

  writeFileSync(
    resolve(CONTRACT_DIR, 'openapi.json'),
    `${JSON.stringify(openapi, null, 2)}\n`,
    'utf8',
  );
  writeFileSync(
    resolve(CONTRACT_DIR, 'money-vectors.json'),
    `${JSON.stringify(buildMoneyVectors(), null, 2)}\n`,
    'utf8',
  );

  const paths = Object.keys((openapi as { paths: Record<string, unknown> }).paths).length;
  process.stdout.write(`contract/openapi.json (${paths} paths)\ncontract/money-vectors.json\n`);
}

await main();
